server:
  port: 3030

spring:
  application:
    name: social-media-demo
  profiles:
    active: dev

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false


  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
    generate-ddl: true
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

#security:
#  jwt:
#    header: Authorization
#    prefix: Bearer
#    expiration: 24*60*60
#    secret: JwtSecretKey




